### ISSUE TITLE
Floop ignores progress if child process logs to stderr

### ISSUE THREAD

**Issue by setcheverry** [d3sw/floop#10] opened 2017-09-01 22:48 UTC
## Expected Behavior
Progress gets reported when underlying process writes progress to stderror.

## Current Behavior
It doesn't show progress with programs that write progress to stderror 

## Possible Solution
A possible solution is to add a flag that will allow progress if it is written to stderror.

## Steps to Reproduce (for bugs)
1. Configure floop to show progress.
2. Run a programs that logs to stderror with floop.
3. Check progress messages.

## Context
Trying to collect progress from Apple iTunes Transporter.

## Your Environment
* Product Version: v0.1.0
* OS and OS Version: CentOS release 6.9 (2.6.32-696.6.3.el6.x86_64)

**Comment by KristinaEtc** [comment] 2017-09-04 09:44
I'll do it

**Comment by euforia** [comment] 2017-09-27 01:14
This is the intended behavior.  A new config option should be added to allow the progress handler to listen to stderr.  I'm closing this one to add a new issue for the config option here #14

**Closed by euforia** 2017-09-27 01:14 UTC
